import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync } from 'node:fs';
import { build } from 'esbuild';
const sqlite = new DatabaseSync(':memory:');
for (const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()) sqlite.exec(readFileSync(`drizzle/${file}`,'utf8'));
const prepare = sql => {
  const stmt = sqlite.prepare(sql);
  return { bind(...values) { return { first:async()=>stmt.get(...values) ?? null, all:async()=>({results:stmt.all(...values)}), run:async()=>({meta:{changes:stmt.run(...values).changes}}) }; } };
};
globalThis.__PROVIDER_TEST_ENV__ = {DB:{prepare,batch:async(statements)=>Promise.all(statements.map(s=>s.run()))},CREDENTIAL_ENCRYPTION_KEY:Buffer.alloc(32,9).toString('base64')};
const output=await build({stdin:{contents:`export * from './db/custom-image-providers'; export * from './db/generation-tasks';`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'test-worker-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env = globalThis.__PROVIDER_TEST_ENV__;'}));}}]});
const m=await import(`data:text/javascript;base64,${Buffer.from(output.outputFiles[0].text).toString('base64')}`);
const body={name:'测试',baseUrl:'https://api.vendor.com/v1',modelName:'image-model',format:'multipart',sizes:'auto,1024x1024',qualities:'',apiKey:'test-secret-key'};
const config=await m.saveCustomProvider('owner-a',body);
assert.equal((await m.listCustomProviders('owner-a')).length,1);
assert.equal((await m.listCustomProviders('owner-b')).length,0);
assert.equal(JSON.stringify(await m.listCustomProviders('owner-a')).includes('test-secret-key'),false);
assert.equal(sqlite.prepare('SELECT encrypted_key FROM custom_image_providers').get().encrypted_key.includes('test-secret-key'),false);
assert.equal((await m.customProvider('owner-a',config.id,true)).apiKey,'test-secret-key');
await assert.rejects(m.customProvider('owner-b',config.id,true));
await assert.rejects(m.saveCustomProvider('owner-b',{...body,id:config.id}));
await assert.rejects(m.saveCustomProvider('owner-a',{...body,id:config.id,baseUrl:'https://new.vendor.com/v1',apiKey:''}),/重新填写/);
const updated=await m.saveCustomProvider('owner-a',{...body,id:config.id,name:'更名',apiKey:''});
assert.notEqual(updated.revision,config.revision);
assert.equal((await m.customProvider('owner-a',config.id,true)).apiKey,'test-secret-key');
const row={id:crypto.randomUUID(),owner_id:'owner-a',name:'新品',status:'uploading',model:`custom-${config.id}`,prompt:'中文',aspect_ratio:'auto',resolution:'1024x1024',color_name:'暖白',created_at:Date.now(),updated_at:Date.now()};
assert.equal(await m.insertTask(row),true);
await assert.rejects(m.saveCustomProvider('owner-a',{...body,id:config.id,apiKey:'new-secret'}),/任务/);
assert.equal((await m.customProvider('owner-a',config.id,true)).apiKey,'test-secret-key');
assert.equal(await m.insertTask({...row,id:crypto.randomUUID()}),false);
assert.equal(await m.claimSubmission('owner-a',row.id),true);
assert.equal(await m.claimSubmission('owner-a',row.id),false);
await m.updateTask('owner-a',row.id,'queued','','custom-result');
const lease=await m.claimPoll('owner-a',row.id);assert.ok(lease);
await m.updateTask('owner-a',row.id,'saving','',null,lease);
await m.completeTask(row,'image/png',68,'owner-a/generated/result',lease);
assert.equal((await m.getTask('owner-a',row.id)).status,'succeeded');
assert.equal(sqlite.prepare('SELECT tags FROM assets WHERE id = ?').get(row.id).tags,'自定义API;组合效果');
await m.completeTask(row,'image/png',68,'owner-a/generated/result',lease);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM assets').get().n,1);
assert.equal(await m.getTask('owner-b',row.id),null);
sqlite.close(); delete globalThis.__PROVIDER_TEST_ENV__;
console.log('PASS: real SQLite migrations, encrypted storage, owner isolation, safe key rotation, revision pinning, active-task lock, asset finalization and idempotency. Memory-only database; no user data touched.');
