import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const built=await build({stdin:{contents:`export * from './lib/detail-template';export * from './lib/production-plan';export {productionDetailFiles} from './db/production';`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'node',format:'cjs',external:['cloudflare:workers'],logLevel:'silent'});
let assetAvailable=true,objectAvailable=true;const lookups=[];
const env={DB:{prepare(sql){return{bind(owner,id){lookups.push({sql,owner,id});return{async first(){return assetAvailable?{object_key:'owned-reference',mime_type:'image/png'}:null;}};}};}},FILES:{async get(){return objectAvailable?{size:2,async arrayBuffer(){return new Uint8Array([1,2]).buffer;}}:null;}}};
const require=createRequire(import.meta.url),m={exports:{}};
new Function('require','module','exports',built.outputFiles[0].text)(name=>name==='cloudflare:workers'?{env}:require(name),m,m.exports);
const {expandedDetails,detailPageOrder,detailDisplayTitle,detailMissing,validateDetailEvidence,detailProductionBrief,initialProductionDraft,validateProductionPlan,planItems,productionDetailFiles}=m.exports;
assert.equal(expandedDetails.length,12);assert.equal(new Set(expandedDetails).size,12);
assert.equal(expandedDetails.at(-1),'规格选择');
const historical=[{id:'image',kind:'detail',title:'新品形象'},{id:'spec',kind:'detail',title:'规格选择',generationId:'keep-generation'},{id:'notice',kind:'detail',title:'选购须知'}];
assert.deepEqual(detailPageOrder(historical).map(i=>i.id),['image','notice','spec']);
assert.equal(detailPageOrder(historical).at(-1),historical[1]);
assert.equal(historical[1].id,'spec');
assert.equal(detailDisplayTitle('规格选择'),'全规格尺寸总览');
const a='12345678-1234-1234-1234-123456789abc',b='abcdef12-1234-1234-1234-123456789abc';
const evidence=validateDetailEvidence({material:'画芯为纱面；框架表面为木纹装饰面。',transparency:'半透可隐约看到背景；不透款遮蔽背景。',refs:{transparency:a,wood:a,back:a,side:b,colors:a}});
for(const title of expandedDetails)assert.deepEqual(detailMissing(title,evidence),[]);
for(const title of ['半透与不透对比','木纹装饰面细节','材质介绍','正反对比','三视图'])assert.ok(detailMissing(title).length);
assert.deepEqual(detailMissing('六种颜色展示'),[]);
assert.throws(()=>validateDetailEvidence({refs:{back:'https://foreign.example/image'}}));
assert.throws(()=>validateDetailEvidence({material:123}));
const draft=initialProductionDraft({product:{name:'测试新品'},sizes:[]});
const config=validateProductionPlan({...draft,confirmed:true,detailEvidence:evidence},[]);
assert.equal(planItems(config).filter(i=>i.kind==='detail').length,12);
assert.equal(config.detailEvidence.material,evidence.material);
const colors=detailProductionBrief('六种颜色展示','规则','',evidence);
for(const name of ['原木','红木色','黄花梨色','胡桃木色','简约灰','暖白色'])assert.ok(colors.includes(name));
assert.ok(colors.includes('画芯与结构不变'));assert.ok(!colors.includes('保持确认样图木色不变'));
assert.ok(detailProductionBrief('材质介绍','','',evidence).includes(evidence.material));
assert.match(detailProductionBrief('正反对比','','',evidence),/不将整件产品镜像当作背面/);
const ctx={row:{title:'三视图'},config:{detailEvidence:evidence}};
const refs=await productionDetailFiles('owner',ctx);assert.equal(refs.length,2);assert.equal(refs[0].label,'同款侧面原图');assert.equal(refs[1].label,'同款背面原图');
assert.ok(lookups.every(x=>x.owner==='owner'&&x.sql.includes("category='详情参考'")&&x.sql.includes('owner_id=?')));
assert.deepEqual(await productionDetailFiles('owner',{row:{title:'三视图'},config:{}}),[]);
for(const refs of [undefined,evidence]){
  const three=detailProductionBrief('三视图','','',refs),back=detailProductionBrief('正反对比','','',refs);
  assert.match(three,/90度正侧视/);assert.match(three,/木纹、.*厚度/);
  assert.doesNotMatch(three,/只做简洁轮廓|只允许明确标记的轮廓|侧面示意/);
  assert.doesNotMatch(back,/采用.*轮廓示意|背面示意，以实物为准/);
  for(const brief of [three,back]){
    assert.match(brief,/图案相对正面左右反向/);assert.match(brief,/颜色稍浅但仍清楚可见/);
    assert.match(brief,/不能变成空白/);assert.match(brief,/不淡化木框、柜体、五金或摆件/);
    assert.match(brief,/不将整件产品镜像当作背面/);
  }
}
assert.match(detailProductionBrief('三视图','',''),/不伪称实拍/);
assert.match(detailProductionBrief('半透与不透对比','',''),/效果示意，实际表现以实物为准/);
assert.match(detailProductionBrief('材质介绍','',''),/不推测实际材料成分/);
assetAvailable=false;await assert.rejects(()=>productionDetailFiles('owner',ctx),/无法读取/);assetAvailable=true;
objectAvailable=false;await assert.rejects(()=>productionDetailFiles('owner',ctx),/不存在/);
const route=readFileSync('app/api/generate-preview/route.ts','utf8');
assert.ok(route.indexOf('await productionDetailFiles(owner,context)')<route.indexOf('await insertTask(row)'));
assert.ok(route.includes('refs.push(ref.file)'));assert.ok(route.includes('context.config.detailEvidence'));
const batch=readFileSync('app/production-batch.tsx','utf8');assert.ok(!batch.includes('detailMissing'));
console.log('PASS 12-module template, optional references with safe illustrative fallback, facts and ownership preserved. No paid calls.');
