import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const result=await build({entryPoints:['app/api/library-originals/[id]/route.ts'],bundle:true,write:false,platform:'node',format:'cjs',external:['cloudflare:workers'],logLevel:'silent'});
const objects=new Map();let writes=0;
const bucket={async get(key){const o=objects.get(key);return o?{body:o.bytes,size:o.bytes.byteLength}:null;},async head(key){const o=objects.get(key);return o?{size:o.bytes.byteLength}:null;},async put(key,bytes){writes++;objects.set(key,{bytes});}};
const m={exports:{}},require=createRequire(import.meta.url);
new Function('require','module','exports',result.outputFiles[0].text)(name=>name==='cloudflare:workers'?{env:{FILES:bucket}}:require(name),m,m.exports);
const {GET,HEAD,PUT}=m.exports;
const index=JSON.parse(readFileSync('public/library/2026-08-27-v2/originals-index.json','utf8').replace(/^\uFEFF/,''));
const [id,entry]=Object.entries(index)[0],ctx={params:Promise.resolve({id})},url='https://test.local/api/library-originals/'+id,bytes=readFileSync(entry.originalDiskFile);
assert.equal((await GET(new Request(url),ctx)).status,404);
assert.equal((await PUT(new Request(url,{method:'PUT',body:bytes,headers:{origin:'https://wrong.local'}}),ctx)).status,403);
assert.equal((await PUT(new Request(url,{method:'PUT',body:new Uint8Array(bytes.length)}),ctx)).status,400);assert.equal(writes,0);
assert.equal((await PUT(new Request(url,{method:'PUT',body:bytes}),ctx)).status,200);assert.equal(writes,1);
assert.equal((await PUT(new Request(url,{method:'PUT',body:bytes}),ctx)).status,200);assert.equal(writes,1);
assert.equal((await HEAD(new Request(url),ctx)).status,200);
assert.deepEqual(Buffer.from(await (await GET(new Request(url),ctx)).arrayBuffer()),bytes);
assert.equal((await PUT(new Request(url,{method:'PUT',body:bytes}),{params:Promise.resolve({id:'../secret'})})).status,404);
assert.equal(writes,1);
console.log('PASS immutable original storage: exact hash and length, no overwrite, unknown IDs and cross-origin rejected; no catalog/history writes.');
