import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
let missing=false;
const built=await build({entryPoints:['lib/production-item-action.ts'],bundle:true,write:false,platform:'node',format:'cjs',plugins:[{name:'references',setup(b){b.onResolve({filter:/studio-reference$/},()=>({path:'references',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:`export const artworkOriginal=a=>a.originalFile;export const readReference=(u,l)=>globalThis.testReference(u,l);`,loader:'js'}));}}]});
const m={exports:{}};new Function('require','module','exports',built.outputFiles[0].text)(createRequire(import.meta.url),m,m.exports);
const {submitProductionItem,watchProductionItem}=m.exports;
const item={id:'item',title:'新品形象',kind:'detail',generationId:'old',task:{id:'old',status:'succeeded',model:'gpt-image-2',aspectRatio:'3:4',resolution:'2k',url:'/api/files/old',recipe:{quality:'high'}}};
const data={product:{id:'p',frameName:'框架'},sample:{recipe:{artworkId:'art',frameId:'frame',colorId:'color'}}};
const input={data,item,artworks:[{id:'art',name:'原画',originalFile:'/original'}],colors:[{id:'color',name:'胡桃',color:'#123456'}],note:'加入摆件',adjust:true};
const calls=[];let active=false,stale=false,ambiguous=false;
globalThis.testReference=async()=>{if(missing)throw Error('原图读取失败');return new File(['x'],'x.png',{type:'image/png'});};
globalThis.fetch=async(url,init)=>{calls.push({url,init});if(url==='/api/production/item')return Response.json(init?.method?{ok:true}:{itemId:'item',productId:'p',generationId:stale?'changed':'old',kind:'detail',frameUrl:'/sample'});if(url==='/api/generations')return Response.json(active?[{status:'running'}]:[]);if(url==='/api/generate-preview'){if(ambiguous)throw Error('连接中断');return Response.json({id:'new',status:'queued'});}if(url==='/api/generations/new')return Response.json({id:'new',status:'succeeded',url:'/new'});throw Error(url);};
assert.equal(await submitProductionItem(input,()=>false),null);assert.ok(!calls.some(c=>c.init?.method==='POST'));
calls.length=0;missing=true;await assert.rejects(()=>submitProductionItem(input,()=>true),/原图/);assert.ok(!calls.some(c=>c.init?.method==='POST'));missing=false;
for(const flag of ['active','stale']){calls.length=0;active=flag==='active';stale=flag==='stale';await assert.rejects(()=>submitProductionItem(input,()=>true));assert.ok(!calls.some(c=>c.init?.method==='POST'));}active=false;stale=false;
calls.length=0;const task=await submitProductionItem(input,()=>true);const posts=calls.filter(c=>c.init?.method==='POST');assert.equal(posts.length,2);assert.equal(JSON.parse(posts[0].init.body).generationId,'old');assert.equal(posts[1].init.body.get('productionItemId'),'item');assert.equal(posts[1].init.body.get('instruction'),'加入摆件');assert.equal(posts[1].init.body.get('quality'),'high');assert.equal(item.generationId,'old');
const progress=[];await watchProductionItem(task,{stopped:()=>false,progress:async t=>progress.push(t.status),wait:async()=>{}});assert.deepEqual(progress,['queued','succeeded']);
calls.length=0;await submitProductionItem({...input,adjust:false,note:''},()=>true);assert.match(calls.find(c=>c.url==='/api/generate-preview').init.body.get('instruction'),/不沿用上一轮临时修改/);
calls.length=0;ambiguous=true;await assert.rejects(()=>submitProductionItem(input,()=>true),/连接中断/);assert.equal(calls.filter(c=>c.url==='/api/generate-preview').length,1);
const view=readFileSync('app/product-workspace.tsx','utf8');assert.ok(!view.includes('href={`/?production='));assert.match(view,/key={item.id}/);
const editor=readFileSync('app/production-item-actions.tsx','utf8');assert.match(editor,/重做这张图/);assert.match(editor,/按要求调整这张图/);assert.ok(!editor.includes('window.location'));
console.log('PASS inline adjust/remake: one item, original settings, cancellation/preflight, no navigation, no billable retries. Mock calls only.');
