import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const {sharedScene,canReuseScene,validSizeMarks,sceneSizeBrief}=await load('../lib/production-scene.ts');
const {validateProductionPlan,planItems}=await load('../lib/production-plan.ts');
const spec={widthCm:60,heightCm:200,depthCm:30,sourceIds:['representative']};
const scene={id:'main',title:'客厅场景',kind:'main',review:'accepted',generationId:'g',task:{status:'succeeded',url:'/api/files/a',model:'gpt-image-2',resolution:'2k',aspectRatio:'1:1'}};
const plan={config:{sceneTitle:'客厅场景'},items:[scene]};
const item={kind:'size',spec};const workspace={sample:{recipe:{frameId:'uploaded-frame-representative'}}};
assert.equal(sharedScene(plan),scene);assert.equal(sharedScene({...plan,items:[{...scene,review:'rework'}]}),undefined);
assert.ok(canReuseScene(item,workspace,plan));assert.ok(!canReuseScene({...item,spec:{...spec,sourceIds:['other']}},workspace,plan));
assert.ok(canReuseScene(item,workspace,{...plan,items:[{...scene,task:{...scene.task,model:'gpt-image-2.5-sunburst'}}]}));
assert.ok(!canReuseScene(item,workspace,{...plan,items:[{...scene,task:{...scene.task,model:'other'}}]}));
const marks={generationId:'g',points:[{x:.3,y:.8},{x:.6,y:.8},{x:.2,y:.1},{x:.2,y:.8},{x:.6,y:.8},{x:.7,y:.75}]};
assert.ok(validSizeMarks(marks,'g',true));assert.ok(!validSizeMarks(marks,'other',true));assert.ok(!validSizeMarks({...marks,points:Array(6)},'g',true));
assert.ok(!validSizeMarks({...marks,points:marks.points.map(()=>({x:2,y:1}))},'g',true));
assert.match(sceneSizeBrief(spec,'only upper',''),/图3为共用场景主图/);assert.match(sceneSizeBrief(spec,'',''),/不沿用图3产品的尺寸或数量/);
const input={name:'test',expectedVersion:0,rule:'upper',notes:'',sizes:[spec],main:['客厅场景'],details:['新品形象'],confirmed:true,sceneTitle:'客厅场景'};
const validated=validateProductionPlan(input,['representative']);assert.equal(validated.sceneTitle,'客厅场景');
assert.throws(()=>validateProductionPlan({...input,main:['白底主图']},['representative']));
assert.match(planItems(validated).find(i=>i.kind==='size').brief,/沿用客厅场景背景/);
assert.match(planItems(validated).find(i=>i.kind==='main').brief,/四周保留标注空间/);
const models=await readFile(new URL('../lib/generation-models.ts',import.meta.url),'utf8');assert.match(models,/defaultImageModel = imageModels.find\(model => model.id === 'gpt-image-2'\)/);
console.log('shared scene, exact-spec reuse, marks validation, scene briefs and GPT Image 2 defaults passed');
