import assert from 'node:assert/strict';
import { build } from 'esbuild';
const compiled = await build({entryPoints:['lib/reference-upload.ts'],bundle:true,write:false,format:'esm',platform:'browser'});
const { referenceUpload } = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
let closed = 0, draws = [], encodes = [];
globalThis.createImageBitmap = async () => ({width:4096,height:4096,close(){closed++;}});
globalThis.document = {createElement(){return {width:0,height:0,getContext(){return {drawImage(...args){draws.push(args.slice(1));},fillRect(){}};},toBlob(cb,type){encodes.push(type);cb(new Blob([new Uint8Array(type==='image/png'?11*1024*1024:1024)],{type}));}};}};
const small = new Blob(['original'],{type:'image/png'});
assert.equal(await (await referenceUpload(small,'small')).text(),'original');
assert.equal(closed,0);
const large = new Blob([new Uint8Array(10965535)],{type:'image/png'});
const copy = await referenceUpload(large,'sample');
assert.equal(large.size,10965535);
assert.equal(copy.type,'image/jpeg');
assert.ok(copy.size<=10*1024*1024);
assert.deepEqual(draws.at(-1),[0,0,4096,4096]);
assert.equal(closed,1);
await referenceUpload(new Blob(['webp'],{type:'image/webp'}),'webp');
assert.ok(encodes.includes('image/png'));
assert.equal(closed,2);
await assert.rejects(referenceUpload(new Blob(['x'],{type:'text/plain'}),'bad'));
console.log('Reference upload: small original preserved; oversized PNG/WebP copied below limit; full aspect ratio retained.');
