import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
const index=JSON.parse(readFileSync('lib/site-asset-index.json','utf8').replace(/^\uFEFF/,''));
assert.equal(Object.keys(index).length,318);
for(const row of Object.values(index))assert.equal(createHash('sha256').update(readFileSync(row.originalDiskFile)).digest('hex'),row.originalHash);
const result=await build({entryPoints:['lib/site-asset-store.ts'],bundle:true,write:false,platform:'node',format:'cjs',external:['cloudflare:workers'],logLevel:'silent'});
const objects=new Map();let writes=0;
const bucket={async get(key){const bytes=objects.get(key);return bytes?{body:bytes,size:bytes.byteLength}:null;},async head(key){const bytes=objects.get(key);return bytes?{size:bytes.byteLength}:null;},async put(key,bytes){writes++;objects.set(key,bytes);}};
const m={exports:{}},require=createRequire(import.meta.url);new Function('require','module','exports',result.outputFiles[0].text)(name=>name==='cloudflare:workers'?{env:{FILES:bucket}}:require(name),m,m.exports);
const {readSiteAsset,writeSiteAsset,headSiteAsset}=m.exports;
const [path,entry]=Object.entries(index)[0],bytes=readFileSync(entry.originalDiskFile),url='https://test.local/api/site-assets/'+entry.originalHash;
assert.equal((await readSiteAsset('/api/secret')).status,404);
assert.equal((await writeSiteAsset(new Request(url,{method:'PUT',body:bytes,headers:{origin:'https://wrong.local'}}),entry.originalHash)).status,403);
assert.equal((await writeSiteAsset(new Request(url,{method:'PUT',body:new Uint8Array(bytes.length)}),entry.originalHash)).status,400);
assert.equal((await writeSiteAsset(new Request(url,{method:'PUT',body:bytes}),entry.originalHash)).status,200);
assert.equal((await writeSiteAsset(new Request(url,{method:'PUT',body:bytes}),entry.originalHash)).status,200);assert.equal(writes,1);
assert.equal((await headSiteAsset(entry.originalHash)).status,200);
assert.deepEqual(Buffer.from(await (await readSiteAsset(path)).arrayBuffer()),bytes);
console.log('PASS 318 preserved static image hashes, unchanged path serving, immutable provisioning, no arbitrary file writes.');
