import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import ts from 'typescript';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');
const compile=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const moduleOf=source=>import('data:text/javascript;base64,'+Buffer.from(compile(source)).toString('base64'));
const models=await moduleOf((await read('../lib/generation-models.ts')).replace("import {internationalCompositionModels} from './international-composition-models';",'const internationalCompositionModels = [];'));
const model=models.getImageModel('gpt-image-2.5-sunburst');
assert.equal(model.endpoint,'/openapi/v2/rhart-image-g-2.5-official-token/sunburst/edit');
assert.equal(models.defaultImageModel.id,'gpt-image-2');
for(const quality of model.qualities)assert.ok(models.validModelSettings(model,'1:1','2k',quality,'auto','png'));
assert.ok(!models.validModelSettings(model,'1:1','8k','max','auto','png'));
assert.ok(!models.validModelSettings(model,'1:1','2k','max','transparent','jpeg'));
assert.ok(!models.validModelSettings(model,'1:1','2k','invalid','auto','png'));
assert.ok(!models.validModelSettings(model,'1:1','2k','high','invalid','png'));
assert.ok(!models.validModelSettings(model,'1:1','2k','high','auto','gif'));
assert.ok(!models.validModelSettings(models.defaultImageModel,'1:1','2k','xhigh'));
assert.ok(!models.validModelSettings(models.defaultImageModel,'1:1','2k','medium','transparent','png'));

// Execute the real submit adapter; no network, no credentials, no paid requests.
const source=await read('../lib/runninghub.ts');
const fn=source.slice(source.indexOf('export async function submitGeneration('),source.indexOf('export async function queryGeneration(')).replace('export ','');
let calls=[];
const context={...models,RUNNINGHUB_MODEL:models.defaultImageModel.id,RUNNINGHUB_ORIGIN:'https://www.runninghub.ai',RunningHubError:Error,
  call:async(...args)=>{calls.push(args);return {taskId:'mock-task',status:'RUNNING'};}};
vm.createContext(context);vm.runInContext(compile(fn),context);
const input={model:model.id,prompt:'严格保留产品，仅更换背景',imageUrls:['https://example.test/ref.png'],aspectRatio:'1:1',resolution:'2k',quality:'xhigh',background:'transparent',outputFormat:'webp'};
const connection={origin:'https://www.runninghub.ai',key:'fake-test-key'};
await context.submitGeneration(input,connection);
assert.equal(calls.length,1);assert.equal(calls[0][0],model.endpoint);
assert.equal(calls[0][1].background,'transparent');assert.equal(calls[0][1].outputFormat,'webp');assert.equal(calls[0][1].quality,'xhigh');
assert.equal(calls[0][2],true);assert.equal(calls[0][3],connection);
await assert.rejects(()=>context.submitGeneration({...input,outputFormat:'jpeg'},connection));
await assert.rejects(()=>context.submitGeneration({...input,imageUrls:Array(17).fill('https://example.test/a')},connection));
await assert.rejects(()=>context.submitGeneration({...input,prompt:'a'.repeat(32001)},connection));
await assert.rejects(()=>context.submitGeneration(input,{...connection,origin:'https://www.runninghub.cn'}));
assert.equal(calls.length,1);
await context.submitGeneration({...input,imageUrls:Array(16).fill('https://example.test/a')},connection);
assert.equal(calls.length,2);
await context.submitGeneration({...input,model:'gpt-image-2',quality:'medium',background:undefined,outputFormat:undefined},connection);
assert.ok(!('background' in calls[2][1]));assert.ok(!('outputFormat' in calls[2][1]));
await context.submitGeneration({...input,quality:undefined,background:undefined,outputFormat:undefined},connection);
assert.equal(calls[3][1].background,'auto');assert.equal(calls[3][1].outputFormat,'png');assert.equal(calls[3][1].quality,'medium');
const recipeModule=await moduleOf(await read('../lib/studio-brief.ts'));
const recipe={artworkId:'a',frameId:'f',colorId:'c',intent:'composition',instruction:'保留结构',background:'transparent',outputFormat:'webp',quality:'xhigh'};
assert.deepEqual(recipeModule.parseRecipe(JSON.stringify(recipe)),recipe);
assert.ok(!('outputFormat' in recipeModule.parseRecipe(JSON.stringify({...recipe,outputFormat:'gif'}))));
const page=await read('../app/page.tsx'),route=await read('../app/api/generate-preview/route.ts');
assert.match(page,/form.set\('background', background\)/);assert.match(page,/form.set\('outputFormat', outputFormat\)/);
assert.match(page,/model.backgrounds\?\.length \? \{background\}/);assert.match(page,/model.outputFormats\?\.length \? \{outputFormat\}/);
assert.match(page,/recipe.background/);assert.match(page,/recipe.outputFormat/);
assert.match(route,/validModelSettings\(model, ratio, resolution, quality, background, outputFormat\)/);
assert.match(route,/model: model.id, quality, background, outputFormat/);
assert.match(route,/本套需要保留场景背景/);
console.log('Sunburst: endpoint, options, defaults, rejected combinations, 16 refs, history, consent and old-model isolation passed (mock only).');
