import { env } from 'cloudflare:workers';
export type CreatorOutput = {key?:string;url?:string;mime?:string;name?:string;text?:string;error?:string};
export type CreatorTask = { id:string;owner_id:string;name:string;endpoint:string;kind:string;status:string;remote_id:string|null;inputs_json:string;outputs_json:string;error:string;cost:string;lease:number;created_at:number;updated_at:number };
export const activeCreatorStatuses=['uploading','submitting','queued','running','saving','unknown'];
export async function creatorTasks(owner:string) {
  await env.DB.prepare("UPDATE rh_creator_tasks SET status='unknown',error='请求是否成功尚未确认，请先到 RunningHub 核对，勿重复生成。',updated_at=? WHERE owner_id=? AND status='submitting' AND updated_at<?").bind(Date.now(),owner,Date.now()-180000).run();
  await env.DB.prepare("UPDATE rh_creator_tasks SET status='failed',error='素材上传中断，未提交生成。',updated_at=? WHERE owner_id=? AND status='uploading' AND updated_at<?").bind(Date.now(),owner,Date.now()-180000).run();
  return (await env.DB.prepare('SELECT * FROM rh_creator_tasks WHERE owner_id=? ORDER BY created_at DESC LIMIT 100').bind(owner).all<CreatorTask>()).results;
}
export async function creatorTask(owner:string,id:string) {return env.DB.prepare('SELECT * FROM rh_creator_tasks WHERE owner_id=? AND id=?').bind(owner,id).first<CreatorTask>();}
export function publicCreatorTask(t:CreatorTask) {return {id:t.id,name:t.name,kind:t.kind,status:t.status,error:t.error,cost:t.cost,remoteId:t.remote_id,createdAt:t.created_at,outputs:(JSON.parse(t.outputs_json) as CreatorOutput[]).map((o,i)=>({...o,key:undefined,url:o.key?`/api/rh-creator/files/${t.id}?index=${i}`:o.url,saved:!!o.key}))};}
export async function insertCreator(t:{id:string;owner:string;name:string;endpoint:string;kind:string;inputs:unknown}) {await env.DB.prepare("INSERT INTO rh_creator_tasks (id,owner_id,name,endpoint,kind,status,inputs_json,created_at,updated_at) VALUES (?,?,?,?,?,'uploading',?,?,?)").bind(t.id,t.owner,t.name,t.endpoint,t.kind,JSON.stringify(t.inputs),Date.now(),Date.now()).run();}
export async function setCreator(owner:string,id:string,status:string,error='',remote?:string,outputs?:CreatorOutput[],cost?:string,lease?:number) {await env.DB.prepare("UPDATE rh_creator_tasks SET status=?,error=?,remote_id=COALESCE(?,remote_id),outputs_json=COALESCE(?,outputs_json),cost=COALESCE(?,cost),updated_at=? WHERE owner_id=? AND id=? AND status NOT IN ('succeeded','failed') AND (? IS NULL OR lease=?)").bind(status,error,remote??null,outputs?JSON.stringify(outputs):null,cost??null,Date.now(),owner,id,lease??null,lease??null).run();}
export async function creatorLease(owner:string,id:string) {const lease=Date.now();const r=await env.DB.prepare("UPDATE rh_creator_tasks SET lease=? WHERE owner_id=? AND id=? AND status IN ('queued','running','saving','unknown') AND remote_id IS NOT NULL AND lease<?").bind(lease,owner,id,lease-120000).run();return r.meta.changes?lease:0;}
export async function releaseCreator(owner:string,id:string,lease:number) {await env.DB.prepare('UPDATE rh_creator_tasks SET lease=0 WHERE owner_id=? AND id=? AND lease=?').bind(owner,id,lease).run();}
const encode=(v:Uint8Array)=>btoa(String.fromCharCode(...v));
const decode=(v:string)=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
async function cipherKey(){if(!env.CREDENTIAL_ENCRYPTION_KEY)throw new Error('安全存储尚未就绪。');return crypto.subtle.importKey('raw',decode(env.CREDENTIAL_ENCRYPTION_KEY),'AES-GCM',false,['encrypt','decrypt']);}
async function keyRow(owner:string){return env.DB.prepare('SELECT encrypted_key FROM rh_creator_keys WHERE owner_id=?').bind(owner).first<{encrypted_key:string}>();}
export async function creatorKeyStatus(owner:string){return {configured:!!(await keyRow(owner)),canSave:!!env.CREDENTIAL_ENCRYPTION_KEY};}
export async function saveCreatorKey(owner:string,key:string){if(!/^[\x21-\x7e]{16,512}$/.test(key))throw new Error('请填写完整 Key，不要包含空格或换行。');const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(`rh-creator:${owner}`)},await cipherKey(),new TextEncoder().encode(key));const r=await env.DB.prepare("INSERT INTO rh_creator_keys (owner_id,encrypted_key,updated_at) SELECT ?,?,? WHERE NOT EXISTS (SELECT 1 FROM rh_creator_tasks WHERE owner_id=? AND status IN ('uploading','submitting','queued','running','saving','unknown')) ON CONFLICT(owner_id) DO UPDATE SET encrypted_key=excluded.encrypted_key,updated_at=excluded.updated_at").bind(owner,`v1.${encode(iv)}.${encode(new Uint8Array(bytes))}`,Date.now(),owner).run();if(!r.meta.changes)throw new Error('请先完成或核对当前任务，再更换 Key。');}
export async function creatorKey(owner:string){const row=await keyRow(owner);if(!row)throw new Error('请先填写 RunningHub 通用模型 Key。');try{const [v,iv,c]=row.encrypted_key.split('.');if(v!=='v1')throw new Error();return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv),additionalData:new TextEncoder().encode(`rh-creator:${owner}`)},await cipherKey(),decode(c)));}catch{throw new Error('已保存的 Key 无法读取，请重新配置。');}}
