import { generationOwner } from '../../../../../lib/generation-auth';
import { creatorKey,creatorTask,creatorLease,releaseCreator,setCreator,publicCreatorTask,type CreatorOutput } from '../../../../../db/rh-creator';
import { rhRequest,archiveCreatorResult,CreatorError,safeMediaUrl } from '../../../../../lib/rh-creator-provider';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}});
export async function GET(_request:Request,context:{params:Promise<{id:string}>}){const owner=await generationOwner();if(!owner)return json({error:'请先登录。'},401);const {id}=await context.params;let lease=0;try{let task=await creatorTask(owner,id);if(!task)return json({error:'记录不存在。'},404);lease=await creatorLease(owner,id);if(lease){
    try{if(task.status!=='saving'){const r=await rhRequest(await creatorKey(owner),'/openapi/v2/query',{taskId:task.remote_id});if(r.status==='FAILED')await setCreator(owner,id,'failed','平台生成失败，请到 RunningHub 核对原因。',undefined,undefined,undefined,lease);else if(r.status==='SUCCESS'){
      const rows=Array.isArray(r.results)?r.results:[];if(!rows.length||rows.length>50)throw new CreatorError('平台未返回可保存的结果，请到官网核对。');
      const out:CreatorOutput[]=rows.map((o:Record<string,unknown>)=>{const url=o.url||o.outputUrl;if(typeof url==='string'){safeMediaUrl(url);return {url};}const text=o.text||o.content||o.output;if(typeof text==='string')return {text:text.slice(0,100000)};return {error:'平台返回格式暂不支持，请到官网下载。'};});
      const cost=r.usage?.consumeMoney??r.usage?.thirdPartyConsumeMoney;await setCreator(owner,id,'saving','',undefined,out,cost===undefined?'':String(cost).slice(0,50),lease);
    }else if(['RUNNING','QUEUED'].includes(r.status))await setCreator(owner,id,r.status.toLowerCase(),'',undefined,undefined,undefined,lease);else throw new CreatorError('平台状态暂未确认，请稍后恢复查询。');}
    task=(await creatorTask(owner,id))!;
    if(task.status==='saving'){const outputs=JSON.parse(task.outputs_json) as CreatorOutput[];const index=outputs.findIndex(o=>o.url&&!o.key);if(index>=0){try{outputs[index]={...outputs[index],...await archiveCreatorResult(owner,id,index,outputs[index].url!,task.kind),error:undefined};}catch(e){outputs[index].error=e instanceof CreatorError?e.message:'保存暂时中断，请点击恢复保存，不会重新收费生成。';}await setCreator(owner,id,'saving','',undefined,outputs,undefined,lease);}if(outputs.every(o=>o.key||o.text))await setCreator(owner,id,'succeeded','',undefined,outputs,undefined,lease);}
    }catch(e){await setCreator(owner,id,(await creatorTask(owner,id))!.status,e instanceof CreatorError?e.message:'查询暂时中断，请恢复查询，不要重复生成。',undefined,undefined,undefined,lease);}finally{await releaseCreator(owner,id,lease);}
  }return json(publicCreatorTask((await creatorTask(owner,id))!));}catch{return json({error:'记录暂不可读取，请稍后重试。'},503);}}
export async function POST(request:Request,context:{params:Promise<{id:string}>}){const owner=await generationOwner(request);if(!owner)return json({error:'请先登录。'},401);const {id}=await context.params;const t=await creatorTask(owner,id);if(!t)return json({error:'记录不存在。'},404);const body=await request.text();if(body==='keep-links'&&t.status==='saving'&&(!t.lease||t.lease<Date.now()-120000)){await setCreator(owner,id,'external','已按用户选择停止保存，仅保留平台链接；链接可能过期。');return json({resolved:true});}if(t.status!=='unknown'||t.remote_id)return json({error:'只能解除没有任务编号的待核对记录。'},409);if(body!=='confirmed-not-submitted')return json({error:'请先到官网核对。'},400);await setCreator(owner,id,'failed','用户已在平台核对并解除锁定；保留此记录。');return json({resolved:true});}
